### ISSUE TITLE
Help in Adjusting Layout

### ISSUE THREAD

**Issue by rajivseelam** [trebuchetty/Handsontable-select2-editor#10]
Hi,

I am using select2 3.5.2 and handsontable latest.

Any ideas on how this problem can be solved? It works fine when the page is loaded for the first time.

![select2-dropdown-2](https://cloud.githubusercontent.com/assets/1103649/8435554/73748946-1f6f-11e5-8fbe-68b101379f63.png)
![select2-dropdown](https://cloud.githubusercontent.com/assets/1103649/8435555/7384cb9e-1f6f-11e5-9c5b-6f94e1f1f5ac.png)

**Comment by rajivseelam** [comment]
Same problem on stackoverflow

http://stackoverflow.com/questions/31239171/select2-dropown-in-handsontable-goes-out-of-layout-cell

**Comment by trebuchetty** [comment]
This issue has been fixed with the latest changes. Closing
