### ISSUE TITLE
Multiple Values - Delete Items

### ISSUE THREAD

**Issue by alejsouza** [trebuchetty/Handsontable-select2-editor#19]
When you use select2 with multilple = true, the selected items can't be deleted 

Configuration example:

{      
            data: 'num',
            editor: 'select2',
            renderer: customDropdownRenderer,
            width: '200px',
            select2Options: { 
                data: optionsList,
                dropdownAutoWidth: true,                        
                width: 'resolve',
                multiple: true
            }

so, the selection is working and customizing the render the multilpes are show, but at the moment to edit and try to delete one item the editor is closed and the item is not deleted. Any way to fix this? Thanks!

**Comment by alejsouza** [comment]
Looks like the problem is the editor z-index value, it is lower than handsontable z-index, so adding this:
    this.textareaParentStyle.zIndex = 20000;

in Select2Editor.prototype.open function solves the problem

**Comment by trebuchetty** [comment]
Thanks, I've added this change into the source.
