### ISSUE TITLE
Id is being display if type is string

### ISSUE THREAD

**Issue by rexghadaffi** [trebuchetty/Handsontable-select2-editor#23]
if the optionList of the select2 is like below / in the example you have given, it works fine.
               var optionsList = [{ id: 1, text: 'first' }, { id: 1, text: 'second' }];

but not with this. it displays the id instead of the text.

```
  var optionsList = [
                      {
                          id: "ab703c8d-57e7-e511-80d1-00155d010e2c", text: "Mirage"
                      }, {
                          id: "ab499fa1-69c5-e511-80cc-00155d010e2c", text: "Sample Base Model"
                      }
      ]
```

**Comment by rexghadaffi** [comment]
try editing your :[jsfiddle](http://jsfiddle.net/mpusarla/4mpyhbjw/35/)

**Comment by trebuchetty** [comment]
This is an issue (not really an issue) with the customDropdownRenderer I made for the sample. The select2Editor still functions as it should. 
In the renderer, you can remove the parseInt and change "===" to "==" and it will work as you wanted it to.
