### ISSUE TITLE
displayed values

### ISSUE THREAD

**Issue by timberswrx** [trebuchetty/Handsontable-select2-editor#5]
I'm not sure where else to ask questions about this editor, so I'll do it here. If there is a better place, let me know.

When I set up the editor similarly to the example code, once I make a selection, the id value is displayed, not the text. How can that be changed? I want to display the text selected.

If I use select2 in a normal form, not handsontable, it works correctly, I get the text displayed. So the problem is only with the select2-editor. Any help would be appreciated.

**Comment by trebuchetty** [comment]
here is as good a place as any. I'm the originator for this editor. 
For displaying the text selected, you'll have to use a handsontable renderer for that. The editor is only for selecting the value.

**Comment by timberswrx** [comment]
Do you have any example code? I've been trying this for a while, and all I get is the ID value returned from this editor. I must be doing something wrong, but I don't know what. I set up this editor exactly like your example, and I see the initial value displayed correctly (from data source). Once I double click on the cell and open this editor, then select one of the displayed values I get the ID value appended to the existing value. I do have it set to multiple. I've tried setting a renderer, but I still get the ID value from this editor. I have not done a lot of javascript, so I'm probably missing something obvious, so example code would be great.

**Comment by mpusarla** [comment]
Here is an example for displaying the text instead of id
http://jsfiddle.net/mpusarla/4mpyhbjw/35/
