### ISSUE TITLE
Tried to implement into my handsontable got errors

### ISSUE THREAD

**Issue by ORLAND0** [trebuchetty/Handsontable-select2-editor#6]
Hello, got TypeError: this.instance.rootElement[0] is undefined on line 41 
think this is because rootElement should not have a [0]? 

Changed that to this.instance.rootElement  then started to get:
TypeError: this.$textarea.select2 is not a function select2-editor.js at 129:8
TypeError: that.instance.registerTimeout is not a function

**Comment by trebuchetty** [comment]
I think there's some issues with this editor and newer versions of handsontable. I've been meaning to get the latest version then update this editor, but haven't had the time. There's been a pull request that someone has done that they believe fixes this issue, you may want to try that.

**Comment by trebuchetty** [comment]
Please take a look at the jsfiddle added to the readme for a sample of this editor working
