### ISSUE TITLE
Working sample?

### ISSUE THREAD

**Issue by Tbaseflug** [trebuchetty/Handsontable-select2-editor#8]
Is there a way to get a working sample?

**Comment by trebuchetty** [comment]
That's a good idea. When I've got some time, I will build a working jsfiddle. That should probably help quite a bit.

**Comment by aadrian** [comment]
Any news on this?

Thanks in advance.

**Comment by trebuchetty** [comment]
I've just updated the readme with a link to jsfiddle of this working with Select2 3.5.2 and Handsontable 0.15.0
