### ISSUE TITLE
What version of Handsontable is this for?

### ISSUE THREAD

**Issue by hansgru** [trebuchetty/Handsontable-select2-editor#9]
Hi,

What version of Handsontable is this component for?

Since there's no package.json or bower.json or some comments, maybe the problems the users encounter are that they're using it with the wrong Handsontable.

**Comment by trebuchetty** [comment]
I agree. That and sometimes it seems that others aren't sure as to how to use this tool, which is on me to improve the documentation

**Comment by trebuchetty** [comment]
I've just added a link in the readme that points to a working jsfiddle example using Select2 3.5.2 and Handsontable 0.15.0
